top_srcdir   = /home/amiya/softwares/httpd-2.4.3
top_builddir = /home/amiya/softwares/httpd-2.4.3
srcdir       = /home/amiya/softwares/httpd-2.4.3/modules/mappers
builddir     = /home/amiya/softwares/httpd-2.4.3/modules/mappers
VPATH        = /home/amiya/softwares/httpd-2.4.3/modules/mappers

include $(top_srcdir)/build/special.mk

