top_srcdir   = /home/amiya/softwares/httpd-2.4.3
top_builddir = /home/amiya/softwares/httpd-2.4.3
srcdir       = /home/amiya/softwares/httpd-2.4.3/modules/metadata
builddir     = /home/amiya/softwares/httpd-2.4.3/modules/metadata
VPATH        = /home/amiya/softwares/httpd-2.4.3/modules/metadata

include $(top_srcdir)/build/special.mk

