top_srcdir   = /home/amiya/softwares/httpd-2.4.3
top_builddir = /home/amiya/softwares/httpd-2.4.3
srcdir       = /home/amiya/softwares/httpd-2.4.3/modules/loggers
builddir     = /home/amiya/softwares/httpd-2.4.3/modules/loggers
VPATH        = /home/amiya/softwares/httpd-2.4.3/modules/loggers

include $(top_srcdir)/build/special.mk

