top_srcdir   = /home/amiya/softwares/httpd-2.4.3
top_builddir = /home/amiya/softwares/httpd-2.4.3
srcdir       = /home/amiya/softwares/httpd-2.4.3/modules/filters
builddir     = /home/amiya/softwares/httpd-2.4.3/modules/filters
VPATH        = /home/amiya/softwares/httpd-2.4.3/modules/filters

include $(top_srcdir)/build/special.mk

