top_srcdir   = /home/amiya/softwares/httpd-2.4.3
top_builddir = /home/amiya/softwares/httpd-2.4.3
srcdir       = /home/amiya/softwares/httpd-2.4.3/modules/cluster
builddir     = /home/amiya/softwares/httpd-2.4.3/modules/cluster
VPATH        = /home/amiya/softwares/httpd-2.4.3/modules/cluster
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
