top_srcdir   = /home/amiya/softwares/httpd-2.4.3
top_builddir = /home/amiya/softwares/httpd-2.4.3
srcdir       = /home/amiya/softwares/httpd-2.4.3/modules/core
builddir     = /home/amiya/softwares/httpd-2.4.3/modules/core
VPATH        = /home/amiya/softwares/httpd-2.4.3/modules/core

include $(top_srcdir)/build/special.mk

