top_srcdir   = /home/amiya/softwares/httpd-2.4.3
top_builddir = /home/amiya/softwares/httpd-2.4.3
srcdir       = /home/amiya/softwares/httpd-2.4.3/modules/http
builddir     = /home/amiya/softwares/httpd-2.4.3/modules/http
VPATH        = /home/amiya/softwares/httpd-2.4.3/modules/http

include $(top_srcdir)/build/special.mk

