top_srcdir   = /home/amiya/softwares/httpd-2.4.3
top_builddir = /home/amiya/softwares/httpd-2.4.3
srcdir       = /home/amiya/softwares/httpd-2.4.3/server/mpm
builddir     = /home/amiya/softwares/httpd-2.4.3/server/mpm
VPATH        = /home/amiya/softwares/httpd-2.4.3/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
